FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm i -g npm@11.13.0 && npm install --omit=dev

COPY server ./server

ENV NODE_ENV=production
EXPOSE 5050

CMD ["npm", "run", "server"]
